#!/bin/bash
#
# uninstall.sh - Uninstaller for Wi-Fi AutoConfig for Hammerspoon
#
# Usage:
#   bash uninstall.sh              Interactive uninstall (prompts for config backup)
#   bash uninstall.sh --force      Skip prompts, backup config to Desktop
#   bash uninstall.sh --help       Show help
#
set -e

# ============================================================================
# Configuration
# ============================================================================
HAMMERSPOON_DIR="$HOME/.hammerspoon"
HAMMERSPOON_INIT="$HAMMERSPOON_DIR/init.lua"
INSTALL_DIR="$HAMMERSPOON_DIR/wifi_autoconfig"
BACKUP_DIR="${BACKUP_DIR:-$HOME/.wifi_autoconfig_backups}"
BACKUP_FILE="$BACKUP_DIR/wifi_autoconfig_config_backup.json"

# The passwordless sudo rules install.sh may have written. Left behind, they keep
# granting NOPASSWD root over the network configuration after the module is gone, so
# the uninstaller owns these files too - but only the ones carrying install.sh's
# marker (see SUDOERS_MARKER): the older names are one or two characters away from
# rules a person may have written for another tool, and deleting those would take
# away a permission nobody asked this uninstaller to touch.
# Kept in sync with install.sh, which writes them.
SUDOERS_D="/etc/sudoers.d"
SUDOERS_FILE="$SUDOERS_D/hammerspoon_wificonfig"
LEGACY_SUDOERS_FILES="$SUDOERS_D/hammerspoon_netconfig $SUDOERS_D/hammerspoon_network"
SUDOERS_MARKER='# Generated by install.sh'

# A live reference to the module in init.lua, in either form people write it. The
# uninstaller must remove what the installer injected - including an assignment like
# `local m = require("wifi_autoconfig.init")`, which would otherwise leave Hammerspoon
# erroring on every reload after the module directory is gone.
MODULE_REF_PATTERN='^[[:space:]]*((local[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*([[:space:]]*,[[:space:]]*[A-Za-z_][A-Za-z0-9_]*)*[[:space:]]*=[[:space:]]*)?require[[:space:]]*\(?[[:space:]]*["'\'']wifi_autoconfig'
INIT_CLEAN_PATTERN="$MODULE_REF_PATTERN|^[[:space:]]*--+[[:space:]]*Wi-Fi AutoConfig for Hammerspoon[[:space:]]*\$"

# Same source of truth build-release.sh reads, so the banner cannot drift from
# the installer again (it said 3.0.0 long after the module reached 3.2.x).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)"
MODULE_VERSION="$(grep -E '^MODULE_VERSION=' "$SCRIPT_DIR/install.sh" 2>/dev/null | head -1 | sed 's/.*="//; s/"$//')"
MODULE_VERSION="${MODULE_VERSION:-unknown}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================================================
# Helpers
# ============================================================================
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
step()  { echo -e "${BLUE}[STEP]${NC} $1"; }

# Is a terminal actually attached? /dev/tty keeps existing as a character device when
# nothing is behind it, and `-c /dev/tty` still says yes, so the only honest test is to
# open it. A failed redirect is reported by the shell to its own stderr, which a
# command-level 2>/dev/null cannot hide - hence the subshell.
has_tty() {
    ( exec </dev/tty ) 2>/dev/null
}

# Ask a question even when the script arrived over a pipe (curl | bash), where stdin
# is the script body: a bare `read` there consumes the next command line as the answer
# and bash carries on after it, silently skipping the rest of the uninstall.
# Returns 0 when the user was actually asked, 1 when there is nobody to ask.
ask_line() {
    local prompt="$1"
    REPLY=""
    if [ -t 0 ]; then
        read -r -p "$prompt" REPLY || true
        return 0
    elif has_tty && read -r -p "$prompt" REPLY </dev/tty 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

# Reads a sudoers.d drop-in into SUDOERS_CONTENT. These files are root:wheel 0440, so
# a normal user cannot read them and `cat` is not in the passwordless rule; asking sudo
# is the only way to learn whether a leftover file is one this installer wrote, which is
# exactly what decides whether it may be deleted. Returns 1 when nothing could be read.
read_sudoers_file() {
    local f="$1"
    SUDOERS_CONTENT=""
    if [ -r "$f" ]; then
        SUDOERS_CONTENT="$(cat "$f" 2>/dev/null)"
    elif sudo -n cat "$f" >/dev/null 2>&1; then
        SUDOERS_CONTENT="$(sudo -n cat "$f" 2>/dev/null)"
    elif has_tty; then
        SUDOERS_CONTENT="$(sudo cat "$f" </dev/tty 2>/dev/null)"
    fi
    [ -n "$SUDOERS_CONTENT" ]
}

# Every drop-in this module may have written: the name it manages, the names older
# builds used, and anything else whose name points at this project. Listing the
# directory needs no privilege, so this finds the files; reading them may.
sudoers_candidates() {
    local f
    for f in "$SUDOERS_FILE" $LEGACY_SUDOERS_FILES "$SUDOERS_D"/*hammerspoon* \
             "$SUDOERS_D"/*wificonfig* "$SUDOERS_D"/*networksetup*; do
        [ -f "$f" ] && echo "$f"
    done | sort -u
}

show_help() {
    cat <<'EOF'
Wi-Fi AutoConfig for Hammerspoon uninstaller

Removes the module directory and its reference in ~/.hammerspoon/init.lua, and
deletes the passwordless sudoers rules that install.sh wrote. Run it even if the
module directory is already gone - the sudo rule and the init.lua line outlive it
and keep taking effect.

Sudoers drop-ins are only deleted when they carry install.sh's own marker
("# Generated by install.sh"). A similar-looking file written by hand or by another
tool is printed instead, with the command to remove it, and left in place.
Deleting a sudoers file needs root, so sudo may ask for your password once; if it is
refused the file stays and the summary says so.

Usage:
  bash uninstall.sh              Interactive uninstall
  bash uninstall.sh --force      Skip prompts: auto-backup config to
                                 ~/.wifi_autoconfig_backups/ and remove the
                                 sudoers rules install.sh wrote
  bash uninstall.sh --help       Show this help message
EOF
}

# ============================================================================
# Backup config.json to ~/.wifi_autoconfig_backups/
# ============================================================================
backup_config() {
    if [ -f "$INSTALL_DIR/config.json" ]; then
        mkdir -p "$BACKUP_DIR"
        cp "$INSTALL_DIR/config.json" "$BACKUP_FILE"
        info "Config backed up to: $BACKUP_FILE"
    fi
}

# ============================================================================
# Remove the passwordless sudo rules for /usr/sbin/networksetup
#   The files are root-owned (0440), so only root can delete them - this script
#   cannot do it silently. The commands are printed when sudo is refused so the
#   user is never left with a permission they did not agree to keep.
#   Only files carrying install.sh's marker are deleted; the rest are shown.
# ============================================================================
remove_sudoers_rule() {
    local force="$1"
    local found=""
    local f

    while IFS= read -r f; do
        if [ -n "$f" ]; then found="$found $f"; fi
    done <<< "$(sudoers_candidates)"

    if [ -z "$found" ]; then
        info "No sudoers rule in this module's name - nothing to remove."
        return 0
    fi

    step "Removing the passwordless sudo rule the installer wrote..."

    local ours="" foreign="" foreign_info="" line
    for f in $found; do
        if ! read_sudoers_file "$f"; then
            foreign="$foreign $f"
            foreign_info="${foreign_info}  $f (could not read without a password)
    Check it: sudo cat $f
    Remove it only if it is yours: sudo rm -f $f
"
            continue
        fi
        if grep -qF "$SUDOERS_MARKER" <<< "$SUDOERS_CONTENT"; then
            ours="$ours $f"
        else
            foreign="$foreign $f"
            foreign_info="${foreign_info}  $f:"
            while IFS= read -r line; do
                foreign_info="${foreign_info}    | $line
"
            done <<< "$SUDOERS_CONTENT"
            foreign_info="${foreign_info}    Check it: sudo cat $f
    Remove it only if it is yours: sudo rm -f $f
"
        fi
    done

    if [ -n "$foreign" ]; then
        warn "Leaving these alone: they do not carry install.sh's marker, so they may"
        warn "belong to another tool or to a rule you wrote yourself."
        while IFS= read -r line; do
            if [ -n "$line" ]; then warn "$line"; fi
        done <<< "$foreign_info"
    fi

    if [ -z "$ours" ]; then
        if [ -n "$foreign" ]; then
            warn "No file here was written by install.sh, so nothing was removed."
        fi
        return 0
    fi

    for f in $ours; do
        warn "  $f grants: sudo /usr/sbin/networksetup <IP/DNS/DHCP/IPv6> without a password"
    done

    if [ "$force" = "true" ]; then
        REPLY="y"
    elif ask_line "  Remove these now? (Y/n) "; then
        [[ $REPLY =~ ^[Nn]$ ]] && REPLY="n" || REPLY="y"
    else
        info "No terminal to ask on: removing them as part of the uninstall."
        REPLY="y"
    fi

    if [ "$REPLY" = "y" ]; then
        local left=""
        for f in $ours; do
            if sudo rm -f "$f" 2>/dev/null; then
                info "  Removed $f"
            else
                left="$left $f"
            fi
        done
        if [ -n "$left" ]; then
            warn "Could not remove:$left (need root). Run:"
            for f in $left; do warn "    sudo rm -f $f"; done
        fi
    else
        warn "Kept. The rule still grants passwordless network changes. Remove it later:"
        for f in $ours; do warn "    sudo rm -f $f"; done
    fi
    return 0
}

# ============================================================================
# Remove module directory
# ============================================================================
remove_module() {
    if [ ! -d "$INSTALL_DIR" ]; then
        warn "Module directory not found: $INSTALL_DIR"
        return 0
    fi

    step "Removing $INSTALL_DIR..."
    rm -rf "$INSTALL_DIR"
    info "Module files removed."
}

# ============================================================================
# Clean init.lua (remove require line)
# ============================================================================
clean_init_lua() {
    if [ ! -f "$HAMMERSPOON_INIT" ]; then
        return 0
    fi

    # Two anchored, case-sensitive patterns: a live require() of this module (bare or
    # assigned to a variable) and the comment line install.sh injects next to it. The
    # previous loose substring pattern ('wifi_autoconfig|Wi-Fi AutoConfig', matched
    # case-insensitively) also deleted unrelated user lines that merely mentioned the
    # module - init.lua is the user's own config, so nothing else may be removed here.
    local pattern="$INIT_CLEAN_PATTERN"

    if ! grep -qE "$pattern" "$HAMMERSPOON_INIT" 2>/dev/null; then
        info "No module reference found in init.lua."
        return 0
    fi

    step "Cleaning ~/.hammerspoon/init.lua..."

    info "Lines being removed:"
    grep -nE "$pattern" "$HAMMERSPOON_INIT" | while IFS= read -r line; do
        echo "    | $line"
    done

    mkdir -p "$BACKUP_DIR"
    cp "$HAMMERSPOON_INIT" "$BACKUP_DIR/init.lua.before-uninstall"
    info "init.lua backed up to: $BACKUP_DIR/init.lua.before-uninstall"

    # Built beside the target and renamed over it: mktemp's file in /tmp is mode 0600,
    # and moving that onto init.lua would quietly change its permissions.
    local tmp_file="$HAMMERSPOON_INIT.uninstall.tmp.$$"
    if ! cp -p "$HAMMERSPOON_INIT" "$tmp_file" 2>/dev/null; then
        error "Could not create a temporary copy beside $HAMMERSPOON_INIT; init.lua left untouched."
        error "Remove the require line yourself if it is still there: $HAMMERSPOON_INIT"
        return 0
    fi
    grep -vE "$pattern" "$HAMMERSPOON_INIT" > "$tmp_file" || true

    # Leave the file in place even if only comments remain (don't break other modules)
    mv -f "$tmp_file" "$HAMMERSPOON_INIT"
    info "Removed module references from init.lua."
}

# ============================================================================
# Reload Hammerspoon
# ============================================================================
reload_hammerspoon() {
    if pgrep -x Hammerspoon > /dev/null 2>&1; then
        step "Reloading Hammerspoon..."
        osascript -e 'tell application "Hammerspoon" to execute lua code "hs.reload()"' 2>/dev/null || \
        osascript -e 'tell application "Hammerspoon" to reload' 2>/dev/null || true
        info "Hammerspoon config reloaded."
    fi
}

# ============================================================================
# Main
# ============================================================================
main() {
    local force=false

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --force|-f)
                force=true
                shift
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done

    echo ""
    echo -e "${YELLOW}  Wi-Fi AutoConfig for Hammerspoon v${MODULE_VERSION} uninstaller${NC}"
    echo -e "${YELLOW}  =====================================${NC}"
    echo ""

    # "The module directory is missing" is not "there is nothing to clean up". A
    # hand-deleted or crashed install can leave the require line in init.lua and a live
    # NOPASSWD sudoers rule behind, and those two are what keeps affecting the machine
    # after the module is gone - so the cleanup below runs regardless of the directory,
    # and only the module-specific prompts depend on it.
    if [ ! -d "$INSTALL_DIR" ] && [ -z "$(sudoers_candidates)" ] && \
       ! grep -qE "$INIT_CLEAN_PATTERN" "$HAMMERSPOON_INIT" 2>/dev/null; then
        warn "Nothing to uninstall here: no module directory, no sudoers rule in this"
        warn "project's name, and no reference in $HAMMERSPOON_INIT."
        exit 0
    fi

    if [ -d "$INSTALL_DIR" ]; then
        if [ "$force" = "true" ]; then
            backup_config
        else
            if [ -f "$INSTALL_DIR/config.json" ]; then
                if ask_line "Back up config.json to $BACKUP_DIR before uninstalling? (Y/n) "; then
                    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                        backup_config
                    else
                        warn "config.json will be deleted with the module."
                    fi
                else
                    info "No terminal to ask on: keeping a backup before deleting."
                    backup_config
                fi
            fi

            echo ""
            if ask_line "Confirm uninstall Wi-Fi AutoConfig for Hammerspoon? (y/N) "; then
                if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                    info "Uninstall cancelled."
                    exit 0
                fi
            else
                error "Not uninstalling: there was no terminal to confirm on."
                error "Run this from a terminal, or pass --force to skip the prompts."
                exit 1
            fi
        fi
    else
        warn "Module directory not found at $INSTALL_DIR; removing what it left behind."
    fi

    remove_module
    clean_init_lua
    remove_sudoers_rule "$force"
    reload_hammerspoon

    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}  Wi-Fi AutoConfig for Hammerspoon UNINSTALLED${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    if [ -f "$BACKUP_FILE" ]; then
        echo "  Config backup: $BACKUP_FILE"
    fi

    # Reported from what is actually on disk now, not from what this script tried to do:
    # a sudoers file this script cannot delete (it needs root, and sudo may have been
    # refused) is a permission still being granted, and the summary has to say so.
    local still_there line
    still_there="$(sudoers_candidates)"
    if [ -n "$still_there" ]; then
        echo "  Sudo rules:    STILL PRESENT - passwordless network changes remain granted:"
        while IFS= read -r line; do
            if [ -n "$line" ]; then echo "                   $line"; fi
        done <<< "$still_there"
        echo "                   Inspect: sudo cat <file>   Remove: sudo rm -f <file>"
    else
        echo "  Sudo rules:    none left in this project's name."
    fi

    if grep -qE "$MODULE_REF_PATTERN" "$HAMMERSPOON_INIT" 2>/dev/null; then
        echo "  init.lua:      a module reference is STILL there - the module files are"
        echo "                 gone, so this line would error on every reload. Remove it"
        echo "                 by hand: $HAMMERSPOON_INIT"
    else
        echo "  init.lua:      no module reference left."
    fi

    echo "  Hammerspoon itself was NOT removed."
    echo "  To reinstall: bash install.sh"
    echo ""
}

main "$@"
